name: Stock Analysis Workflow

on:
  schedule:
    # GitHub ActionsのcronはUTC基準です。
    # UTC 0:00 = JST 9:00 (日本時間の朝9時)
    - cron: '0 0 * * *'
  workflow_dispatch: # 手動実行ボタン

jobs:
  build:
    runs-on: ubuntu-latest
    # タイムゾーンをJSTに設定（ログ等の時刻表示用）
    env:
      TZ: 'Asia/Tokyo'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Analysis and Notify
      env:
        CHANNEL_ACCESS_TOKEN: ${{ secrets.CHANNEL_ACCESS_TOKEN }}
        MY_USER_ID: ${{ secrets.MY_USER_ID }}
        # Slack/Discord等は必要に応じて設定
        
      run: |
        # batch_analysis.py が JSONデータを出力し、
        # notify.py がそれを受け取って Flex Message として送信します
        python batch_analysis.py | python notify.py --title "株価分析レポート"